trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'foggycam-kareem:$(build.buildID)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
